#!/usr/bin/env python3
"""
Auto-Generated Evolved Mattress Pattern
========================================
Generated by evolve_optimal_mattress.py
Fitness: 309.1761
Generation: 20
"""

import numpy as np


class EvolvedOptimalPattern:
    """Evolved optimal pressure redistribution pattern."""

    name = "Evolved Optimal"
    pattern_type = "evolved"

    # Region parameters (evolved)
    REGIONS = {
        'head': {
            'bounds': (0.0, 0.08, 0.3, 0.7),
            'cycle_speed': 3.017,
            'wave_type': 'sine',
            'phase_offset': 0.748,
            'min_inflation': 0.032,
            'max_inflation': 0.776,
        },
        'scapulae': {
            'bounds': (0.1, 0.25, 0.2, 0.8),
            'cycle_speed': 0.635,
            'wave_type': 'sine',
            'phase_offset': 0.272,
            'min_inflation': 0.000,
            'max_inflation': 0.600,
        },
        'thoracic': {
            'bounds': (0.25, 0.4, 0.25, 0.75),
            'cycle_speed': 4.260,
            'wave_type': 'sine',
            'phase_offset': 0.296,
            'min_inflation': 0.016,
            'max_inflation': 0.733,
        },
        'sacrum': {
            'bounds': (0.4, 0.55, 0.35, 0.65),
            'cycle_speed': 2.267,
            'wave_type': 'sine',
            'phase_offset': 0.581,
            'min_inflation': 0.186,
            'max_inflation': 0.600,
        },
        'thighs': {
            'bounds': (0.55, 0.75, 0.2, 0.8),
            'cycle_speed': 2.201,
            'wave_type': 'sine',
            'phase_offset': 0.368,
            'min_inflation': 0.000,
            'max_inflation': 0.665,
        },
        'calves': {
            'bounds': (0.75, 0.92, 0.25, 0.75),
            'cycle_speed': 3.729,
            'wave_type': 'triangle',
            'phase_offset': 0.062,
            'min_inflation': 0.000,
            'max_inflation': 0.770,
        },
        'left_heel': {
            'bounds': (0.92, 1.0, 0.3, 0.42),
            'cycle_speed': 3.109,
            'wave_type': 'triangle',
            'phase_offset': 0.580,
            'min_inflation': 0.043,
            'max_inflation': 0.897,
        },
        'right_heel': {
            'bounds': (0.92, 1.0, 0.58, 0.7),
            'cycle_speed': 1.120,
            'wave_type': 'sine',
            'phase_offset': 0.721,
            'min_inflation': 0.141,
            'max_inflation': 0.736,
        },
        'default': {
            'bounds': (0.0, 1.0, 0.0, 1.0),
            'cycle_speed': 2.615,
            'wave_type': 'triangle',
            'phase_offset': 0.584,
            'min_inflation': 0.000,
            'max_inflation': 0.690,
        },
    }

    def get_cell_state(self, row: int, col: int, rows: int, cols: int, phase: float,
                        smooth: bool = False) -> float:
        """Calculate cell inflation based on evolved parameters.

        Args:
            row, col: Cell position
            rows, cols: Grid dimensions
            phase: Current cycle phase (0-1)
            smooth: If True, use smooth transitions for visualization
        """
        row_pos = row / rows
        col_pos = col / cols

        # Find active region
        active_region = 'default'
        for region, params in self.REGIONS.items():
            if region == 'default':
                continue
            r0, r1, c0, c1 = params['bounds']
            if r0 <= row_pos < r1 and c0 <= col_pos <= c1:
                active_region = region
                break

        params = self.REGIONS[active_region]
        local_phase = (phase * params['cycle_speed'] + params['phase_offset']) % 1.0

        # Apply wave type
        wave_type = params['wave_type']
        if wave_type == 'sine':
            wave = 0.5 + 0.5 * np.cos(2 * np.pi * local_phase)
        elif wave_type == 'square':
            if smooth:
                # Smooth square wave using sigmoid-like transition
                k = 20
                wave = 1.0 / (1.0 + np.exp(k * (local_phase - 0.25))) + \
                       1.0 / (1.0 + np.exp(-k * (local_phase - 0.75))) - 1.0
                wave = np.clip(wave, 0, 1)
            else:
                wave = 1.0 if local_phase < 0.5 else 0.0
        elif wave_type == 'triangle':
            wave = 1.0 - 2 * abs(local_phase - 0.5)
        elif wave_type == 'sawtooth':
            wave = 1.0 - local_phase
        else:
            wave = 0.5

        # Scale to inflation range
        return params['min_inflation'] + wave * (params['max_inflation'] - params['min_inflation'])
