#!/usr/bin/env python3
"""
Auto-Generated Evolved Mattress Pattern
========================================
Generated by evolve_optimal_mattress.py
Fitness: 0.4308
Generation: 24
"""

import numpy as np


class EvolvedOptimalPattern:
    """Evolved optimal pressure redistribution pattern."""

    name = "Evolved Optimal"
    pattern_type = "evolved"

    # Region parameters (evolved)
    REGIONS = {
        'head': {
            'bounds': (0.0, 0.08, 0.3, 0.7),
            'cycle_speed': 2.595,
            'wave_type': 'square',
            'phase_offset': 0.649,
            'min_inflation': 0.000,
            'max_inflation': 0.613,
        },
        'scapulae': {
            'bounds': (0.1, 0.25, 0.2, 0.8),
            'cycle_speed': 3.700,
            'wave_type': 'square',
            'phase_offset': 0.985,
            'min_inflation': 0.000,
            'max_inflation': 1.000,
        },
        'thoracic': {
            'bounds': (0.25, 0.4, 0.25, 0.75),
            'cycle_speed': 3.856,
            'wave_type': 'triangle',
            'phase_offset': 0.895,
            'min_inflation': 0.027,
            'max_inflation': 0.600,
        },
        'sacrum': {
            'bounds': (0.4, 0.55, 0.35, 0.65),
            'cycle_speed': 3.434,
            'wave_type': 'sawtooth',
            'phase_offset': 0.931,
            'min_inflation': 0.156,
            'max_inflation': 0.973,
        },
        'thighs': {
            'bounds': (0.55, 0.75, 0.2, 0.8),
            'cycle_speed': 1.178,
            'wave_type': 'sawtooth',
            'phase_offset': 0.992,
            'min_inflation': 0.040,
            'max_inflation': 1.000,
        },
        'calves': {
            'bounds': (0.75, 0.92, 0.25, 0.75),
            'cycle_speed': 3.667,
            'wave_type': 'sawtooth',
            'phase_offset': 0.766,
            'min_inflation': 0.000,
            'max_inflation': 0.685,
        },
        'left_heel': {
            'bounds': (0.92, 1.0, 0.3, 0.42),
            'cycle_speed': 0.500,
            'wave_type': 'square',
            'phase_offset': 0.633,
            'min_inflation': 0.121,
            'max_inflation': 0.889,
        },
        'right_heel': {
            'bounds': (0.92, 1.0, 0.58, 0.7),
            'cycle_speed': 2.265,
            'wave_type': 'sine',
            'phase_offset': 0.076,
            'min_inflation': 0.221,
            'max_inflation': 0.767,
        },
        'default': {
            'bounds': (0.0, 1.0, 0.0, 1.0),
            'cycle_speed': 3.284,
            'wave_type': 'triangle',
            'phase_offset': 0.487,
            'min_inflation': 0.133,
            'max_inflation': 0.617,
        },
    }

    def get_cell_state(self, row: int, col: int, rows: int, cols: int, phase: float,
                        smooth: bool = False) -> float:
        """Calculate cell inflation based on evolved parameters.

        Args:
            row, col: Cell position
            rows, cols: Grid dimensions
            phase: Current cycle phase (0-1)
            smooth: If True, use smooth transitions for visualization
        """
        row_pos = row / rows
        col_pos = col / cols

        # Find active region
        active_region = 'default'
        for region, params in self.REGIONS.items():
            if region == 'default':
                continue
            r0, r1, c0, c1 = params['bounds']
            if r0 <= row_pos < r1 and c0 <= col_pos <= c1:
                active_region = region
                break

        params = self.REGIONS[active_region]
        local_phase = (phase * params['cycle_speed'] + params['phase_offset']) % 1.0

        # Apply wave type
        wave_type = params['wave_type']
        if wave_type == 'sine':
            wave = 0.5 + 0.5 * np.cos(2 * np.pi * local_phase)
        elif wave_type == 'square':
            if smooth:
                # Smooth square wave using sigmoid-like transition
                k = 20  # Steepness
                wave = 1.0 / (1.0 + np.exp(k * (local_phase - 0.25))) + \
                       1.0 / (1.0 + np.exp(-k * (local_phase - 0.75))) - 1.0
                wave = np.clip(wave, 0, 1)
            else:
                wave = 1.0 if local_phase < 0.5 else 0.0
        elif wave_type == 'triangle':
            wave = 1.0 - 2 * abs(local_phase - 0.5)
        elif wave_type == 'sawtooth':
            wave = 1.0 - local_phase
        else:
            wave = 0.5

        # Scale to inflation range
        return params['min_inflation'] + wave * (params['max_inflation'] - params['min_inflation'])
