#!/usr/bin/env python3
"""
Auto-Generated Evolved Mattress Pattern
========================================
Generated by evolve_optimal_mattress.py
Fitness: 0.4440
Generation: 0
"""

import numpy as np


class EvolvedOptimalPattern:
    """Evolved optimal pressure redistribution pattern."""

    name = "Evolved Optimal"
    pattern_type = "evolved"

    # Region parameters (evolved)
    REGIONS = {
        'head': {
            'bounds': (0.0, 0.08, 0.3, 0.7),
            'cycle_speed': 3.206,
            'wave_type': 'sawtooth',
            'phase_offset': 0.347,
            'min_inflation': 0.285,
            'max_inflation': 0.822,
        },
        'scapulae': {
            'bounds': (0.1, 0.25, 0.2, 0.8),
            'cycle_speed': 2.375,
            'wave_type': 'square',
            'phase_offset': 0.592,
            'min_inflation': 0.169,
            'max_inflation': 0.892,
        },
        'thoracic': {
            'bounds': (0.25, 0.4, 0.25, 0.75),
            'cycle_speed': 3.274,
            'wave_type': 'square',
            'phase_offset': 0.012,
            'min_inflation': 0.024,
            'max_inflation': 0.740,
        },
        'sacrum': {
            'bounds': (0.4, 0.55, 0.35, 0.65),
            'cycle_speed': 3.910,
            'wave_type': 'triangle',
            'phase_offset': 0.354,
            'min_inflation': 0.039,
            'max_inflation': 0.721,
        },
        'thighs': {
            'bounds': (0.55, 0.75, 0.2, 0.8),
            'cycle_speed': 1.436,
            'wave_type': 'sawtooth',
            'phase_offset': 0.759,
            'min_inflation': 0.206,
            'max_inflation': 0.711,
        },
        'calves': {
            'bounds': (0.75, 0.92, 0.25, 0.75),
            'cycle_speed': 2.861,
            'wave_type': 'triangle',
            'phase_offset': 0.645,
            'min_inflation': 0.235,
            'max_inflation': 0.851,
        },
        'left_heel': {
            'bounds': (0.92, 1.0, 0.3, 0.42),
            'cycle_speed': 2.372,
            'wave_type': 'sine',
            'phase_offset': 0.333,
            'min_inflation': 0.102,
            'max_inflation': 0.972,
        },
        'right_heel': {
            'bounds': (0.92, 1.0, 0.58, 0.7),
            'cycle_speed': 0.791,
            'wave_type': 'sawtooth',
            'phase_offset': 0.968,
            'min_inflation': 0.181,
            'max_inflation': 0.734,
        },
        'default': {
            'bounds': (0.0, 1.0, 0.0, 1.0),
            'cycle_speed': 2.415,
            'wave_type': 'square',
            'phase_offset': 0.069,
            'min_inflation': 0.120,
            'max_inflation': 0.876,
        },
    }

    def get_cell_state(self, row: int, col: int, rows: int, cols: int, phase: float,
                        smooth: bool = False) -> float:
        """Calculate cell inflation based on evolved parameters.

        Args:
            row, col: Cell position
            rows, cols: Grid dimensions
            phase: Current cycle phase (0-1)
            smooth: If True, use smooth transitions for visualization
        """
        row_pos = row / rows
        col_pos = col / cols

        # Find active region
        active_region = 'default'
        for region, params in self.REGIONS.items():
            if region == 'default':
                continue
            r0, r1, c0, c1 = params['bounds']
            if r0 <= row_pos < r1 and c0 <= col_pos <= c1:
                active_region = region
                break

        params = self.REGIONS[active_region]
        local_phase = (phase * params['cycle_speed'] + params['phase_offset']) % 1.0

        # Apply wave type
        wave_type = params['wave_type']
        if wave_type == 'sine':
            wave = 0.5 + 0.5 * np.cos(2 * np.pi * local_phase)
        elif wave_type == 'square':
            if smooth:
                # Smooth square wave using sigmoid-like transition
                k = 20
                wave = 1.0 / (1.0 + np.exp(k * (local_phase - 0.25))) + \
                       1.0 / (1.0 + np.exp(-k * (local_phase - 0.75))) - 1.0
                wave = np.clip(wave, 0, 1)
            else:
                wave = 1.0 if local_phase < 0.5 else 0.0
        elif wave_type == 'triangle':
            wave = 1.0 - 2 * abs(local_phase - 0.5)
        elif wave_type == 'sawtooth':
            wave = 1.0 - local_phase
        else:
            wave = 0.5

        # Scale to inflation range
        return params['min_inflation'] + wave * (params['max_inflation'] - params['min_inflation'])
